services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: 'postgresql://myuser:mypassword@database:5432/mydatabase?schema=public'
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - '3000:3000'
      - '4000:4000'
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
