services:
  database2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.db
    image: tea79/nodejs2024q3service:db-ver3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - app-network

  app2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: tea79/nodejs2024q3service:app-ver3
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-network
    depends_on:
      - database2

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
