services:
  database:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.db
    image: tea79/nodejs2024q3service:database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: tea79/nodejs2024q3service:latest
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
